title: Davina Stephens
short_title: Davina
subtitle: ""
description: "Davina Stephens’ art is permeated by locally significant elements and atmospheres while evocating a global sensibility. Her celebration of the freedom of living, through story telling, the tropical travels scenes and her use of colour, conveys, using different materials, media and techniques, a unique recognisable character which took her artworks to international recognition."
keywords: acrylic, woodblocks, canvas, archipelago, painter, painting, New Zealander, New Zealand artist
lang: en
version: 1.2.0
baseurl: ""
url: "https://davinastephens.com"
qr: show # 'show' or 'hide' put qr.svg in includes/defs.html call it: icn--qr

company:
  name: #
  legal_name: #if overrides 'company.name' in footer
  email: davinastephensart@gmail.com
  telephone:
  telephone_whatsapp: +1 208 309 0921 #
  fax: #
  address:
  maplink: #
  country: #
  twitter: #
  facebook_page: https://web.facebook.com/davinastephensart
  youtube: https://www.youtube.com/user/davinastephensart
  instagram: https://www.instagram.com/davinastephensart
  vimeo:
  booking: #complete URL
  airbnb: #complete URL
  gplus: #
  tumblr: #
  soundcloud: #complete URL

#SEO https://jekyll.github.io/jekyll-seo-tag/usage/
#
# SEO tag will use the YAML front matter if included in a post, page, or document:
#
# title
# description
# image - (e.g., /assets/page-pic.jpg)
# author - Page-specific author (see below)
# lang - Page-specific language

author: rokma
twitter:
  username: rokmatwit
facebook:
  app_id: #Facebook app ID for Facebook insights
  publisher: #Facebook page URL or ID of the publishing entity
  admins: #Facebook user ID for domain insights linked to a personal account
logo: /assets/favicons/apple-touch-icon-152x152.png

google:
  analytics: UA-137047155-1
  analyticsG4: G-DECX8MBMF8
  verification: google32e66f1a5601ec40

# Build settings
markdown: kramdown
plugins:
  - jekyll/tagging
  - jekyll-seo-tag
  - jekyll-sitemap
  - html-proofer

exclude:
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - Gemfile

permalink: /:title/ # pretty

collections:
  series:
    output: true
    permalink: /:title/
  about:
    output: true
    permalink: /:title/
  pages:
    output: true
    permalink: /:title/

defaults:
  - scope:
      type: posts
    values:
      layout: "painting"

tag_page_layout: post_index_tag
tag_page_dir: ./
tag_permalink_style: pretty
ignored_tags:
